### ISSUE TITLE
Hello BerndiVader.

### ISSUE THREAD

**Issue by MyDreamIsDeveloper** [BerndiVader/NoRunNoDungeon#3]
It's not suitable for writing here, but there's no way to contact you.

I really need the MythicSkripAddon you made.

However, the download link is currently invalid.

If you still have the data, could you release the jar file?

I beg you.

**Comment by BerndiVader** [comment]
Hello! I have updated the repository. But still behind and untested. It uses MM 4.12.0, Skript 2.8.0 and Spigot 1.16.5. It might work with recent Spigot Versions too. Greetings, Berndi.

**Comment by MyDreamIsDeveloper** [comment]
Thanks a million for your assistance.

much appreciated!!

**Comment by BerndiVader** [comment]
Hello, i have updated the whole plugin to work with MythicMobs 5.5.1 and Spigot 1.20.4

**Comment by MyDreamIsDeveloper** [comment]
Thank you for your efforts. A great developer
